// AUTO-GENERATED by contracts/scripts/deploy.ts — do not edit by hand.
// Falls back to env / placeholder until the contract is deployed.
export const TRADING_GAME_ADDRESS =
  process.env.NEXT_PUBLIC_TRADING_GAME_ADDRESS || "0x0000000000000000000000000000000000000000";
export const TRADING_GAME_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_marginToken", type: "address" },
      { internalType: "address", name: "_oracleSigner", type: "address" },
      { internalType: "address", name: "_feeRecipient", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "bytes32", name: "pairId", type: "bytes32" }],
    name: "onlySupportedPair",
    type: "modifier",
  },
] as const;
export const DEPLOYED_CHAIN_ID = parseInt(process.env.NEXT_PUBLIC_CHAIN_ID || "11155111", 10);
