import { ethers, network } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address, "network:", network.name, "chainId:", network.config.chainId);

  const marginToken = process.env.MARGIN_TOKEN_ADDRESS;
  const oracleSigner = process.env.ORACLE_SIGNER_ADDRESS;
  const feeRecipient = process.env.FEE_RECIPIENT_ADDRESS || deployer.address;
  if (!marginToken) throw new Error("MARGIN_TOKEN_ADDRESS not set");
  if (!oracleSigner) throw new Error("ORACLE_SIGNER_ADDRESS not set");

  const TradingGame = await ethers.getContractFactory("TradingGame");
  const game = await TradingGame.deploy(marginToken, oracleSigner, feeRecipient);
  await game.waitForDeployment();
  const addr = await game.getAddress();
  console.log("TradingGame deployed to:", addr);

  for (const p of ["SOL-PERP", "BTC-PERP", "ETH-PERP"]) {
    const id = ethers.keccak256(ethers.toUtf8Bytes(p));
    const tx = await game.adminSetPair(id, true, 1000);
    await tx.wait();
    console.log(`  pair enabled: ${p} -> ${id}`);
  }

  const tx = await game.adminSetRiskParams(40, 40, 1);
  await tx.wait();
  console.log("  risk params set: +40% / -40% / 1% fee");

  const fs = require("fs");
  const path = require("path");
  const abi = (await ethers.getContractAt("TradingGame", addr)).interface.formatJson();
  const outDir = path.join(__dirname, "..", "..", "web", "src", "lib");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const out = `// AUTO-GENERATED by contracts/scripts/deploy.ts
export const TRADING_GAME_ADDRESS = "${addr}";
export const TRADING_GAME_ABI = ${abi} as const;
export const DEPLOYED_CHAIN_ID = ${network.config.chainId};
`;
  fs.writeFileSync(path.join(outDir, "contract.generated.ts"), out);
  console.log("  ABI written to web/src/lib/contract.generated.ts");
}

main().catch((e) => { console.error(e); process.exit(1); });
